### ISSUE TITLE
Solidify API & Variable Names

### ISSUE THREAD

**Issue by FarnazH** [theochem/iodata#41] opened 2019-01-25 22:10 UTC
We should make the necessary changes to vague and long variable names... See issue #1

**Comment by FarnazH** [comment] 2019-01-28 00:15
#1

**Comment by tovrstra** [comment] 2019-01-28 19:37
I'll make a list of additional name/API changes w.r.t #1:

**Name changes**
- `numbers` -> `atnums`
- `pseudonombers` -> `atecpnums`
- `coordinates` -> `atcoords`
- `polar` -> `...` (dipole-dipole polarizability matrix)
- `cell` -> `cellvecs` (matrix whose rows or cell vectors, shape `(nvec, 3)`
- `ms2` -> `mult`

**Consolidation of ever-growing number of attributes**
- `mulliken_charges`, `npa_charges`, `esp_charges` -> `atcharges` is a dictionary where the key is a string describing the type of atomic charge and the value is a corresponding array of atomic charges. Keys should be specific and somewhat self-explaining, e.g. `'mulliken'`, `'natural'`, `'lowdin'`, `'hly'`, `'msk'`, etc.
- `one_mo`, `kin`, `na`, `olp` -> `one_body_integrals` is a dictionary where the key is any of `'core'`, `'kin'`, `'na'`, `'olp'`, followed by a suffix `'_ao'` or `'_mo'`
- `two_mo`, `er` -> `two_body_integrals` is a dictionary where the key is any of `'er'`, `'two'`, followed by a suffix `'_ao'` or `'_mo'`
- `dm_*` -> `one_rdm` is a dictionary with various types of 1-particle reduced density matrices. Standard keys are `'scf'`, `'post_scf'`, `'scf_spin'`, `'post_scf_spin'`.

**Things to be removed** because they are not needed at this stage or in the near future
- `links`
- `permutation` and `signs` (See #42)

**New attributes for `IOData`** for generating QC input files, keeping QM/MM in mind)
- `runtype`: `'energy'`, `'opt'`, `'freq'`, ...
- `obasis_name`, e.g. `'6-31g'`, or `'sto-3g'`
- `extcharges`, array with values of external charges, with shape `(nextcharge,)`
- `extcoords`, array with positions of external charges, which shape `(nextcharge, 3)`
- `charge`, the net charge (should not be a new attribute, but something that is coupled to `nelec`.

**New attributes for `IOData`** for reading useful properties out of QC calculations
- `atforces`, forces in Cartesian coordinates, shape `(natom, 3)`
- `athessian`, hessian in Cartesian coordinates, shape `(3*natom, 3*natom)`
- `atmasses`, vector with atomic masses
- `atfixeds`, boolean flags, True for atoms whose positions were not optimized, or for which no Hessian matrix elements were computed. (Does not affect the size of the Hessian.)
- `symmetry_number` the symmetry number of the molecule

**Other API changes**
- See #24 
- See #42

**Comment by tovrstra** [comment] 2019-03-26 19:17
When this is implemented, we should also find a way to get rid of the `# pylint: disable=no-member` lines in most unit tests. This pylint warning is caused by the rather sloppy design of the `IOData` class. (Attributes are not initialized in `__init__`.)

**Comment by tovrstra** [comment] 2019-03-28 17:12
To solve the `no-member` issue, one should in principle just initialize all attributes in the constructor `__init__`, but this would get very tedious for IOData. Some alternatives are discussed in the documentation of the `attr` package: https://www.attrs.org/en/stable/why.html This overview is mainly intended to advocate the usage of the `attr` package, so critical reading is advised. Still `attr` offers a lot of nice features for the IOData class, including:

- `attr` goes well with type hinting, similar to `typing.NamedTuple`. See https://www.attrs.org/en/stable/types.html
- `attr` supports validators, for which we have now our own rather ugly code. See https://www.attrs.org/en/stable/examples.html#validators
- `attr` makes `__slots__` easy, which could be useful to force all data with non-standard names to be put an `extra` dictionary. (I'll comment on it below.) See https://www.attrs.org/en/stable/glossary.html#term-slotted-classes

**Comment by tovrstra** [comment] 2019-03-28 17:14
I've edited the plan to include an `extra` attributes where everything must be stored for which we do not have standard names. This makes it possible to add more attributes to the `IOData` class in future without breaking any code that uses IOData. All allowed attributes should be put in `__slots__`, either manually or with the `attr` package. See https://docs.python.org/3/reference/datamodel.html#slots

**Comment by tovrstra** [comment] 2019-03-28 17:17
I've merged `extcoords` and `extcharges` into one array. One is never used without the other, so putting them into one array would save us from checking the consistency of the sizes of these arrays.

I've also removed (some time ago) the atghost attribute. Ghost atoms can be identified with `atcorenums == 0.0`.

**Comment by tovrstra** [comment] 2019-05-08 05:02
@FarnazH I'll take care of this one soon.

**Comment by tovrstra** [comment] 2019-05-09 17:26
Small change of plan after brief chat with @PaulWAyers : `spinpol=abs(nalpha-nbeta)` will replace `spinmult=1+abs(nalpha+nbeta)` because spin multiplicity is in several cases not a very accurate name.

**Comment by tovrstra** [comment] 2019-05-10 10:26
Small change of plan. `one_ints` and `two_ints` instead of `one_body_integrals` and `two_body_integrals`, similar to `one_rdms` and `two_rdms`.

**Comment by tovrstra** [comment] 2019-05-10 11:59
Small changes: added `lot` and `moments`.

**Closed** 2019-05-10 19:02 UTC
Labels: API breaking

**Comment by tovrstra** [comment] 2020-07-27 07:37
I've renamed `runtype` to `run_type` in the second comment.
